### ISSUE TITLE
Remaining to-do

### ISSUE THREAD

**Issue by bluepeter** [foxandgeese/tiny-agency#1]
- [x] Search console
- [x] GH pages deploy
- [x] full height columns
- [x] weird visual glitch on initial load
- [x] README update
- [x] Submit to Gatsby starter
- [x] Links from core sites
- [x] Contact us
- [x] Rename repo

**Comment by bluepeter** [comment]
<img width="1366" alt="screen shot 2019-02-11 at 8 21 36 pm" src="https://user-images.githubusercontent.com/2158187/52611509-b3246b00-2e3a-11e9-9612-467e080e569d.png">
